cert:
  renewBefore: 360h0m0s
azure:
  enabled: true
  certificateFile: atlantis-test-cert.pfx
vault:
  azure:
    pathPrefix: secret/devops/terraform/azure
atlantis:
  defaultTFVersion: '0.12.21'
  atlantisUrl: https://atlantis.dsp-devops.broadinstitute.org
  ingress:
    enabled: true
    path: /*
    host: atlantis.dsp-devops.broadinstitute.org
    annotations:
      kubernetes.io/ingress.global-static-ip-name: atlantis-ip
    tls:
      - hosts:
        - atlantis.dsp-devops.broadinstitute.org
        secretName: atlantis-cert
  github:
    user: broadbot
  vcsSecretName: atlantis-github-creds
  googleServiceAccountSecrets:
  - name: atlantis-sa
    secretName: atlantis-sa
  orgWhitelist: 'github.com/broadinstitute/*'
  resources:
    requests:
      memory: 2Gi
      cpu: 100m
    limits:
      memory: 3Gi
      cpu: "3"
  environment:
    ATLANTIS_HIDE_PREV_PLAN_COMMENTS: true
  environmentSecrets:
    - name: TF_VAR_approle_role_id
      secretKeyRef:
        name: atlantis-vault-approle
        key: role-id
    - name: TF_VAR_approle_secret_id
      secretKeyRef:
        name: atlantis-vault-approle
        key: secret-id
    - name: TF_VAR_github_token
      secretKeyRef:
        name: atlantis-github-provider
        key: github-token
    # found in vault at /secret/devops/terraform/azure/atlantis/env
    - name: ARM_CLIENT_ID
      secretKeyRef:
        name: azure-env
        key: ARM_CLIENT_ID
    - name: ARM_CLIENT_CERTIFICATE_PASSWORD
      secretKeyRef:
        name: azure-env
        key: ARM_CLIENT_CERTIFICATE_PASSWORD
    - name: ARM_TENANT_ID
      secretKeyRef:
        name: azure-env
        key: ARM_TENANT_ID

  # found in vault at secret/devops/terraform/azure/certificate
  extraVolumes:
    - name: azure-certificate
      secret:
        secretName: azure-cert
  extraVolumeMounts:
    - name: azure-certificate
      subPath: atlantis-test-sp.pfx
      readOnly: true
      mountPath: /var/secrets/azure/atlantis-test-sp.pfx
  repoConfig: |
    ---
    repos:
    - id: /.*/
      apply_requirements: [mergeable, approved]
      workflow: default
      allowed_overrides: [workflow]
      allow_custom_workflows: true
