enabled: true
vaultLocation: https://clotho.broadinstitute.org:8200
vaultVersion: kv1
serviceAccount:
  create: true
rbac:
  create: true
existingSecret: secret-manager-approle
existingRoleIdKey: role-id
existingSecretIdKey: secret-id
