terra-prometheus:
  # TLS Values
  vaultCert:
    enabled: true
    cert:
      path: secret/dsde/firecloud/dev/common/server.crt
      secretKey: value
    key:
      path: secret/dsde/firecloud/dev/common/server.key
      secretKey: value
    chain:
      path: secret/common/ca-bundle.crt
      secretKey: chain
  prometheus-operator:
    fullnameOverride: "terra-prometheus-operator"
    prometheusOperator:
      createCustomResource: false
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.global-static-ip-name: terra-dev-prometheus-ip
          kubernetes.io/ingress.allow-http: "false"
        hosts:
          - "prometheus.dsde-dev.broadinstitute.org"
        paths:
          - /*
        tls:
          - secretName: terra-prometheus-cert
      service:
        annotations:
          cloud.google.com/backend-config: '{"ports": {"9090": "prometheus-cloud-armor"}}'
        type: NodePort
      prometheusSpec:
        externalUrl: https://prometheus.dsde-dev.broadinstitute.org
        containers:
          - name: stackdriver-exporter
            image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.7.5
            imagePullPolicy: Always
            args:
              - --stackdriver.project-id=broad-dsde-dev
              - --prometheus.wal-directory=prometheus/wal
              - --stackdriver.kubernetes.location=us-central1-a
              - --stackdriver.kubernetes.cluster-name=terra-dev
              #- \"--stackdriver.generic.location=us-central1\"
              #- \"--stackdriver.generic.namespace=terra-stackdriver-k8s\"
              - --include='{__name__=~"kube_node_status_condition"}' # Used for cluster health alert
            ports:
              - name: stackdriver-exp
                containerPort: 9091
            volumeMounts:
              - name: prometheus-terra-prometheus-operator-prometheus-db
                mountPath: /prometheus