install-secrets-manager:
  enabled: false
terra-cluster-networking:
  enabled: false
terra-cluster-storage:
  enabled: false
terra-prometheus:
  # TLS Values
  vaultCert:
    enabled: true
    cert:
      path: secret/dsde/firecloud/dev/common/server.crt
      secretKey: value
    key:
      path: secret/dsde/firecloud/dev/common/server.key
      secretKey: value
    chain:
      path: secret/common/ca-bundle.crt
      secretKey: chain
  # Prometheus-to-sd specifically used for sending kube state metrics to stackdriver
  prometheusToSD:
    metricsSources:
      kube-state-metrics: http://terra-cluster-dev-kube-state-metrics.monitoring:8080
  kube-prometheus-stack:
    fullnameOverride: "terra-prometheus-operator"
    alertmanager:
      enabled: false
      alertmanagerSpec:
        configSecret: terra-prometheus-alertmanager-config
    # disable bad scrape target
    kubelet:
      serviceMonitor:
        resource: false
    prometheusOperator:
      createCustomResource: false
      admissionWebhooks:
        enabled: false # known issue with GKE clusters
      tlsProxy:
        enabled: false #
    grafana:
      namespaceOverride: monitoring
      env:
        GF_SERVER_DOMAIN: "k8s-sys-graph.dsde-dev.broadinstitute.org"
        GF_SERVER_ROOT_URL: "https://k8s-sys-graph.dsde-dev.broadinstitute.org"
        GF_USERS_AUTO_ASSIGN_ORG_ROLE: "Viewer"
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.global-static-ip-name: terra-dev-k8s-sys-graph-ip
          kubernetes.io/ingress.allow-http: "false"
        hosts:
          - "k8s-sys-graph.dsde-dev.broadinstitute.org"
        path: /*
        tls:
          - secretName: terra-prometheus-cert
      service:
        type: NodePort
        annotations:
          cloud.google.com/backend-config: '{"ports": {"80": "prometheus-cloud-armor"}}'
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.global-static-ip-name: terra-dev-prometheus-ip
          kubernetes.io/ingress.allow-http: "false"
        hosts:
          - "prometheus.dsde-dev.broadinstitute.org"
        paths:
          - /*
        tls:
          - secretName: terra-prometheus-cert
      service:
        annotations:
          cloud.google.com/backend-config: '{"ports": {"9090": "prometheus-cloud-armor"}}'
        type: NodePort
      prometheusSpec:
        externalLabels:
          cluster: terra-dev
          environment: dev
        externalUrl: https://prometheus.dsde-dev.broadinstitute.org
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        ruleSelector: {}
        ruleNamespaceSelector: {}
        containers:
          - name: stackdriver-exporter
            image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.7.5
            imagePullPolicy: Always
            args:
              - --stackdriver.project-id=broad-dsde-dev
              - --prometheus.wal-directory=prometheus/wal
              - --stackdriver.kubernetes.location=us-central1-a
              - --stackdriver.kubernetes.cluster-name=terra-dev
              #- \"--stackdriver.generic.location=us-central1\"
              #- \"--stackdriver.generic.namespace=terra-stackdriver-k8s\"
              - --include={sd_export!="false",__name__!~"container_.*|scrape_.*|node_.*|prober_.*|instance:.*|code_.*|mixin_.*|cluster_.*|metrics_.*|java_lang.*|machine_.*|namespace_.*",__name__=~".+"}
              - --include={__name__=~"kube_node_status_condition"} # Used for cluster health alert
            ports:
              - name: stackdriver-exp
                containerPort: 9091
            volumeMounts:
              - name: prometheus-terra-prometheus-operator-prometheus-db
                mountPath: /prometheus
diskmanager:
  enabled: false
  config:
    googleProject: broad-dsde-dev
  nodeSelector:
    bio.terra/node-pool: cronjob
  tolerations:
  - key: "bio.terra/workload"
    operator: Equal
    value: cronjob
    effect: NoSchedule
  vault:
    pathPrefix: secret/dsde/firecloud/dev
