cockroachdb:
  enabled: false
  statefulset:
    resources:
      limits:
        memory: "8Gi"
      requests:
        memory: "8Gi"
  conf:
    cache: "2Gi"
    max-sql-memory: "2Gi"

install-secrets-manager:
  enabled: true
  vaultLocation: https://clotho.broadinstitute.org:8200
  vaultVersion: kv1
  serviceAccount:
    create: true
  rbac:
    create: true
  # kubectl create secret generic secret-manager-approle --from-literal=role-id=*** --from-literal=secret-id=***
  existingSecret: secret-manager-approle
  existingRoleIdKey: role-id
  existingSecretIdKey: secret-id
