terra-cluster-networking:
  enabled: false
terra-prometheus:
  resourceValidator:
    ignore: true
  # TLS Values
  vaultCert:
    enabled: true
    cert:
      path: secret/dsde/firecloud/perf/common/server.crt
      secretKey: value
    key:
      path: secret/dsde/firecloud/perf/common/server.key
      secretKey: value
    chain:
      path: secret/common/ca-bundle.crt
      secretKey: chain
  kube-prometheus-stack:
    fullnameOverride: "terra-prometheus-operator"
    alertmanager:
      alertmanagerSpec:
        configSecret: terra-prometheus-alertmanager-config
    # disable bad scrape target
    kubelet:
      serviceMonitor:
        resource: false
    prometheusOperator:
      createCustomResource: false
      admissionWebhooks:
        enabled: false # known issue with GKE clusters
      tlsProxy:
        enabled: false #
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.global-static-ip-name: terra-perf-prometheus-ip
          kubernetes.io/ingress.allow-http: "false"
        hosts:
          - "prometheus.dsde-perf.broadinstitute.org"
        paths:
          - /*
        tls:
          - secretName: terra-prometheus-cert
      service:
        annotations:
          cloud.google.com/backend-config: '{"ports": {"9090": "prometheus-cloud-armor"}}'
        type: NodePort
      prometheusSpec:
        externalLabels:
          cluster: terra-perf
          environment: perf
        externalUrl: https://prometheus.dsde-perf.broadinstitute.org
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        ruleSelectorNilUsesHelmValues: false
        ruleSelector: {}
        ruleNamespaceSelector: {}
        containers:
          - name: stackdriver-exporter
            image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.7.5
            imagePullPolicy: Always
            args:
              - --stackdriver.project-id=broad-dsde-perf
              - --prometheus.wal-directory=prometheus/wal
              - --stackdriver.kubernetes.location=us-central1-a
              - --stackdriver.kubernetes.cluster-name=terra-perf
              #- \"--stackdriver.generic.location=us-central1\"
              #- \"--stackdriver.generic.namespace=terra-stackdriver-k8s\"
              - --include={sd_export!="false",__name__!~"container_.*|scrape_.*|node_.*|prober_.*|instance:.*|code_.*|mixin_.*|cluster_.*",__name__=~".+"}
              - --include={__name__=~"kube_node_status_condition"} # Used for cluster health alert
            ports:
              - name: stackdriver-exp
                containerPort: 9091
            volumeMounts:
              - name: prometheus-terra-prometheus-operator-prometheus-db
                mountPath: /prometheus