terra-cluster-networking:
  gateway:
    name: template-gateway
terra-prometheus:
  certManager:
    enabled: true
    dnsNames: "prometheus.integ.envs.broadinstitute.org"
  kube-prometheus-stack:
    fullnameOverride: "terra-prometheus-operator"
    prometheusOperator:
      createCustomResource: false
      admissionWebhooks:
        enabled: false # known issue with GKE clusters
      tlsProxy:
        enabled: false #
    prometheus:
      ingress:
        enabled: true
        annotations:
          kubernetes.io/ingress.global-static-ip-name: terra-integ-prometheus-ip
          kubernetes.io/ingress.allow-http: "false"
        hosts:
          - "prometheus.integ.envs.broadinstitute.org"
        paths:
          - /*
        tls:
          - secretName: terra-prometheus-cert
      service:
        annotations:
          cloud.google.com/backend-config: '{"ports": {"9090": "prometheus-cloud-armor"}}'
        type: NodePort
      prometheusSpec:
        externalUrl: https://prometheus.integ.envs.broadinstitute.org
        serviceMonitorSelectorNilUsesHelmValues: false
        serviceMonitorSelector: {}
        serviceMonitorNamespaceSelector: {}
        podMonitorSelectorNilUsesHelmValues: false
        podMonitorSelector: {}
        podMonitorNamespaceSelector: {}
        containers:
          - name: stackdriver-exporter
            image: gcr.io/stackdriver-prometheus/stackdriver-prometheus-sidecar:0.7.5
            imagePullPolicy: Always
            args:
              - --stackdriver.project-id=terra-kernel-k8s
              - --prometheus.wal-directory=prometheus/wal
              - --stackdriver.kubernetes.location=us-central1-a
              - --stackdriver.kubernetes.cluster-name=terra-integration
              #- \"--stackdriver.generic.location=us-central1\"
              #- \"--stackdriver.generic.namespace=terra-stackdriver-k8s\"
              - --include={sd_export!="false",__name__!~"container_.*|scrape_.*|node_.*|prober_.*|instance:.*|code_.*|mixin_.*|cluster_.*",__name__=~".+"}
              - --include={__name__=~"kube_node_status_condition"} # Used for cluster health alert
            ports:
              - name: stackdriver-exp
                containerPort: 9091
            volumeMounts:
              - name: prometheus-terra-prometheus-operator-prometheus-db
                mountPath: /prometheus