defaultDockerConfig: privilegedSidecar

runnerDefaults:
  metadata:
    annotations:
      cluster-autoscaler.kubernetes.io/safe-to-evict: true
  spec:
    nodeSelector:
      cloud.google.com/gke-nodepool: ci-runners-v1

runners:
  - name: dsp-grafana
    repository: broadinstitute/dsp-grafana
    minReplicas: 1
    maxReplicas: 1
  - name: revere
    repository: broadinstitute/revere
  - name: workspace-manager
    repository: DataBiosphere/terra-workspace-manager
  - name: terra-gcs-bq-streaming-functions
    repository: DataBiosphere/terra-gcs-bq-streaming-functions 
  - name: cromwell
    repository: broadinstitute/cromwell
    configOverrides:
      spec:
        resources:
          requests:
            cpu: "4"
            memory: "16Gi"
          limits:
            cpu: "4"
            memory: "16Gi"
