vault:
  logitUrlPath: secret/dsde/firecloud/dev/common/logitapi
filebeat:
  imageTag: 6.8.13
  filebeatConfig:
    filebeat.yml: |
      filebeat.inputs:
      - type: docker
        containers.ids:
         - "*"
        processors:
        - add_kubernetes_metadata:
            host: ${NODE_NAME}
            matchers:
            - logs_path:
                logs_path: "/var/log/containers/"
        - drop_event:
            when:
              not:
                equals:
                  kubernetes.namespace: terra-dev
      output.logstash:
        hosts: ["${LOGIT_URL}:18460"]
        loadbalance: true
        worker: 2    
         